spring:
  jpa:
    hibernate:
      ddl-auto: update

    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5433/LibraryApp
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

server:
  servlet:
    encoding:
      charset: UTF-8